name: Deploy Infrastructure

on:
  workflow_dispatch:
    inputs:
      current_environment:
        type: string
        default: prod

permissions:
  id-token: write
  contents: read

env:
  CONFIG_FULL_RESOURCE_GROUP_NAME: ${{ format('resource_group_name=rg-{0}-{1}', secrets.RESOURCE_GROUP_NAME, inputs.current_environment) }}
  CONFIG_FULL_STORAGE_ACCOUNT_NAME: ${{ format('storage_account_name=st{0}{1}', secrets.STORAGE_ACCOUNT_NAME, inputs.current_environment) }}
  CONFIG_BLOB_CONTAINER_NAME: ${{ format('container_name={0}', secrets.BLOB_CONTAINER_NAME) }}
  CONFIG_KEY: ${{ format('key={0}.terraform.{1}', inputs.current_environment, secrets.BLOB_CONTAINER_NAME) }}
  TF_VAR_resource_group_name: ${{ secrets.RESOURCE_GROUP_NAME }}
  TF_VAR_environment: ${{ inputs.current_environment }}
  TF_VAR_location: ${{ secrets.LOCATION }}
  TF_VAR_resource_group_import_id: ${{ secrets.RESOURCE_GROUP_IMPORT_ID }}
  TF_VAR_storage_account_name: ${{ secrets.STORAGE_ACCOUNT_NAME }}
  TF_VAR_account_tier: ${{ secrets.ACCOUNT_TIER }}
  TF_VAR_account_replication_type: ${{ secrets.ACCOUNT_REPLICATION_TYPE }}
  TF_VAR_storage_account_import_id: ${{ secrets.STORAGE_ACCOUNT_IMPORT_ID }}
  TF_VAR_virtual_network_name: ${{ secrets.VIRTUAL_NETWORK_NAME }}
          
jobs: 
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    environment: ${{ inputs.current_environment }}

    defaults:
        run:
          shell: bash

    steps:

    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Login to Azure using OIDC
      uses: azure/login@v2
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Setup TFLint
      uses: terraform-linters/setup-tflint@v1
    
    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
      continue-on-error: true  

    - name: Terraform Init
      id: init
      run: |
        terraform init \
        -backend-config ${{ env.CONFIG_FULL_RESOURCE_GROUP_NAME }} \
        -backend-config ${{ env.CONFIG_FULL_STORAGE_ACCOUNT_NAME }} \
        -backend-config ${{ env.CONFIG_BLOB_CONTAINER_NAME }} \
        -backend-config ${{ env.CONFIG_KEY }}
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_USE_OIDC: true

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: Init TFLint
      run: tflint --init

    - name: Run TFLint
      run: tflint -f compact

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color --out=out.tfplan
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        ARM_USE_OIDC: true

    - name: Upload the plan
      uses: actions/upload-artifact@v3
      with:
        name: tf-plan
        path: ./out.tfplan

  terraform-apply:
    name: Terraform Apply
    needs: [ terraform-plan ]
    runs-on: ubuntu-latest
    environment: ${{ inputs.current_environment }}

    defaults:
      run:
        shell: bash

    steps:

      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Login to Azure using OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        id: init
        run: |
          terraform init \
          -backend-config ${{ env.CONFIG_FULL_RESOURCE_GROUP_NAME }} \
          -backend-config ${{ env.CONFIG_FULL_STORAGE_ACCOUNT_NAME }} \
          -backend-config ${{ env.CONFIG_BLOB_CONTAINER_NAME }} \
          -backend-config ${{ env.CONFIG_KEY }}
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_USE_OIDC: true

      - name: Download the plan
        uses: actions/download-artifact@v3
        with:
          name: tf-plan
          path: ./

      - name: Apply the plan
        id: apply
        run: terraform apply -no-color -auto-approve out.tfplan
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_USE_OIDC: true


