name: Deploy Infrastructure

on:
  workflow_dispatch:
    inputs:
      current_environment:
        type: string
        default: prod

permissions:
  id-token: write
  contents: read
            
jobs: 
  terraform:
    runs-on: ubuntu-latest

    environment: ${{ inputs.current_environment }}

    defaults:
        run:
          shell: bash
    
    env:
      FULL_RESOURCE_GROUP_NAME: ${{ format('resource_group_name={0}-{1}', secrets.RESOURCE_GROUP_NAME, inputs.current_environment) }}
      FULL_STORAGE_ACCOUNT_NAME: ${{ format('storage_account_name={0}{1}', secrets.STORAGE_ACCOUNT_NAME, inputs.current_environment) }}
      BLOB_CONTAINER_NAME: ${{ format('container_name={0}', secrets.BLOB_CONTAINER_NAME) }}
      KEY: ${{ format('key={0}.terraform.{1}', inputs.current_environment, secrets.BLOB_CONTAINER_NAME) }}
      USE_OIDC: "use_oidc=true"
      SUBSCRIPTION_ID: ${{ format('subscription_id={0}', secrets.AZURE_SUBSCRIPTION_ID) }}
      TENANT_ID: ${{ format('tenant_id={0},', secrets.AZURE_TENANT_ID) }}
      TF_VAR_resource_group_import_id: ${{ secrets.RESOURCE_GROUP_IMPORT_ID }}
      TF_VAR_starage_account_import_id: ${{ secrets.STORAGE_ACCOUNT_IMPORT_ID }}

    steps:

    - uses: actions/checkout@v2

    - name: 'Az CLI login'
      uses: azure/login@v2
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      id: init
      run: |
        terraform init \
        -backend-config=$FULL_RESOURCE_GROUP_NAME \
        -backend-config=$FULL_STORAGE_ACCOUNT_NAME \
        -backend-config=$BLOB_CONTAINER_NAME \
        -backend-config=$KEY \
        -backend-config=$USE_OIDC \
        -backend-config=$SUBSCRIPTION_ID \
        -backend-config=$TENANT_ID \
        -input=false
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_USE_OIDC: true