name: Deploy Infrastructure

on:
  workflow_dispatch:
    inputs:
      current_environment:
        type: string
        default: prod

permissions:
  id-token: write
  contents: read

env:
  tf_actions_working_dir: infra
  CONFIG_FULL_RESOURCE_GROUP_NAME: ${{ format('resource_group_name={0}-{1}', secrets.RESOURCE_GROUP_NAME, inputs.current_environment) }}
  CONFIG_FULL_STORAGE_ACCOUNT_NAME: ${{ format('storage_account_name={0}{1}', secrets.STORAGE_ACCOUNT_NAME, inputs.current_environment) }}
  CONFIG_BLOB_CONTAINER_NAME: ${{ format('container_name={0}', secrets.BLOB_CONTAINER_NAME) }}
  CONFIG_KEY: ${{ format('key={0}.terraform.{1}', inputs.current_environment, secrets.BLOB_CONTAINER_NAME) }}
  TF_VAR_resource_group_name: ${{ secrets.RESOURCE_GROUP_NAME }}
  TF_VAR_environment: ${{ inputs.current_environment }}
  TF_VAR_location: ${{ secrets.LOCATION }}
  TF_VAR_resource_group_import_id: ${{ secrets.RESOURCE_GROUP_IMPORT_ID }}
  TF_VAR_storage_account_name: ${{ secrets.STORAGE_ACCOUNT_NAME }}
  TF_VAR_account_tier: ${{ secrets.ACCOUNT_TIER }}
  TF_VAR_account_replication_type: ${{ secrets.ACCOUNT_REPLICATION_TYPE }}
  TF_VAR_storage_account_import_id: ${{ secrets.STORAGE_ACCOUNT_IMPORT_ID }}
          
jobs: 
  terraform:
    runs-on: ubuntu-latest
    environment: ${{ inputs.current_environment }}

    defaults:
        run:
          shell: bash
          working-directory: ${{ env.tf_actions_working_dir }}


    steps:

    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Az CLI Login
      uses: azure/login@v2
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      id: init
      run: |
        terraform init \
        -backend-config $CONFIG_FULL_RESOURCE_GROUP_NAME \
        -backend-config $CONFIG_FULL_STORAGE_ACCOUNT_NAME \
        -backend-config $CONFIG_BLOB_CONTAINER_NAME \
        -backend-config $CONFIG_KEY
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_USE_OIDC: true

    - name: Terraform Plan
      id: plan
      run: terraform plan --out=out.tfplan
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        ARM_USE_OIDC: true

    - name: Upload the plan
      uses: actions/upload-artifact@v3
      with:
        name: tf-plan
        path: ${{ env.tf_actions_working_dir }}/out.tfplan
