name: Initialize Backend Terraform State Storage
on: 
  workflow_dispatch

permissions:
      id-token: write
      contents: read

env:
  RESOURCE_GROUP_FULL_NAME: ${{ format('{0}-{1}', secrets.RESOURCE_GROUP_NAME, secrets.ENVIRONMENT_NAME) }}
      
jobs: 
  initialize-state-storage:
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
        run:
          shell: bash

    steps:
        - uses: actions/checkout@v4

        # Execute Azure CLI script of a specific CLI version via file present in your repository.
        - name: Azure CLI script file
          uses: azure/cli@v2
          with:
            azcliversion: 2.30.0
            inlineScript: |
              az group create --name ${{ env.RESOURCE_GROUP_FULL_NAME }} --location ${{ secrets.REGION }}

        #- name: Run init-storage-account.sh
        #  run: bash ./.github/scripts/init-storage-account.sh
        #  env:
        #    REGION: ${{ secrets.REGION }}
        #    ENVIRONMENT_NAME: ${{ secrets.ENVIRONMENT_NAME }}
        #    RESOURCE_GROUP_NAME: ${{ secrets.RESOURCE_GROUP_NAME }}
        #    STORAGE_ACCOUNT_NAME: ${{ secrets.STORAGE_ACCOUNT_NAME }}
        #    TERRAFORM_STATE_BLOB_CONTAINER_NAME: ${{ secrets.TERRAFORM_STATE_BLOB_CONTAINER_NAME }}
        #    STORAGE_ACCOUNT_SKU: ${{ secrets.STORAGE_ACCOUNT_SKU }}
