name: Initialize Backend Terraform State Storage
on: 
  workflow_dispatch:
    inputs:
      current_environment:
        type: string
        default: "prod"

permissions:
      id-token: write
      contents: read
      
jobs: 
  initialize-state-storage:
    runs-on: ubuntu-latest
    environment: ${{ inputs.current_environment }}

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
        run:
          shell: bash

    env:
      FULL_RESOURCE_GROUP_NAME: ${{ format('{0}-{1}', secrets.RESOURCE_GROUP_NAME, inputs.current_environment) }}
      FULL_STORAGE_ACCOUNT_NAME: ${{ format('{0}{1}', secrets.STORAGE_ACCOUNT_PREFIX, inputs.current_environment) }}
      STORAGE_ACCOUNT_SKU: ${{ format('{0}_{1}', secrets.ACCOUNT_TIER, secrets.ACCOUNT_REPLICATION_TYPE) }}

    steps:
        - uses: actions/checkout@v4

        - name: Azure login
          uses: azure/login@v2
          with:
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            
        # Execute Azure CLI script of a specific CLI version via file present in your repository.
        - name: Azure CLI script file
          uses: azure/cli@v2
          with:
            azcliversion: 2.30.0
            inlineScript: |
              az group create --name $FULL_RESOURCE_GROUP_NAME --location ${{ secrets.AZ_CLI_LOCATION }} 
              az storage account create --resource-group $FULL_RESOURCE_GROUP_NAME --name $FULL_STORAGE_ACCOUNT_NAME --sku $STORAGE_ACCOUNT_SKU --encryption-services blob --min-tls-version TLS1_2
              az storage container create --name ${{ secrets.BLOB_CONTAINER_NAME }} --account-name $FULL_STORAGE_ACCOUNT_NAME