name: Run Azure Login with OpenID Connect
on: 
  workflow_dispatch:
    inputs:
      current_environment:
        type: string
        default: "prod"

permissions:
      id-token: write
      contents: read
      
jobs: 
  test-oidc:
    runs-on: ubuntu-latest
    environment: ${{ inputs.current_environment }}
    steps:
    - name: 'Az CLI login'
      uses: azure/login@v2
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
    - name: 'Run Azure CLI commands'
      run: |
          az account show
          az group list
          pwd
